### ISSUE TITLE
[ERROR] ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogStream operation: The specified log stream already exists

### ISSUE THREAD

**Issue by svenikea** [svenikea/python-lambda#1]
It appears that when lambda created the new log stream, another invocation also triggered the lambda. The `cloudwatch.check_logstream_existed` function checks the old log stream with even time and ignores the new log stream name

Here is the full log
```
[ERROR] ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogStream operation: The specified log stream already exists
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 53, in lambda_handler
    cloudwatch.create_new_logstream(log_group_list[i], new_log_stream_name)
  File "/var/task/cloudwatch.py", line 35, in create_new_logstream
    logStreamName=logstream
  File "/var/runtime/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by svenikea** [comment]
The reason why this problem exists is when lambda first spins up an instance to run the code, it runs from top to bottom i.e. loading the modules, initializing variables, and loading the function. 

When the lambda is triggered, it just calls the function ``lambda_handler```. This explains why the `if-else` statement to check for a new log stream always fails at the second invocation.

A workaround to this problem is to put ```new_log_stream_name``` inside the function so that it always creates a new log stream name thus making the part where it checks for old log stream meaningless. Or use a ```try catch``` condition to look for ```Resource Already Exists Exception``` and push to the old log stream, this method will work but it will leave out bad traces on the lambda metrics in cloudwatch
